// Code generated by protoc-gen-go. DO NOT EDIT.
// source: certstore.proto

package certstore

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cba6d88e0c2624b, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type GetResponse struct {
	Value                []byte   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cba6d88e0c2624b, []int{1}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type GetRequest struct {
	Attrib               []*GetRequest_AttributeMapEntry `protobuf:"bytes,1,rep,name=attrib,proto3" json:"attrib,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cba6d88e0c2624b, []int{2}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetAttrib() []*GetRequest_AttributeMapEntry {
	if m != nil {
		return m.Attrib
	}
	return nil
}

type GetRequest_AttributeMapEntry struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest_AttributeMapEntry) Reset()         { *m = GetRequest_AttributeMapEntry{} }
func (m *GetRequest_AttributeMapEntry) String() string { return proto.CompactTextString(m) }
func (*GetRequest_AttributeMapEntry) ProtoMessage()    {}
func (*GetRequest_AttributeMapEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cba6d88e0c2624b, []int{2, 0}
}

func (m *GetRequest_AttributeMapEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest_AttributeMapEntry.Unmarshal(m, b)
}
func (m *GetRequest_AttributeMapEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest_AttributeMapEntry.Marshal(b, m, deterministic)
}
func (m *GetRequest_AttributeMapEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest_AttributeMapEntry.Merge(m, src)
}
func (m *GetRequest_AttributeMapEntry) XXX_Size() int {
	return xxx_messageInfo_GetRequest_AttributeMapEntry.Size(m)
}
func (m *GetRequest_AttributeMapEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest_AttributeMapEntry.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest_AttributeMapEntry proto.InternalMessageInfo

func (m *GetRequest_AttributeMapEntry) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *GetRequest_AttributeMapEntry) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "certstore.Empty")
	proto.RegisterType((*GetResponse)(nil), "certstore.GetResponse")
	proto.RegisterType((*GetRequest)(nil), "certstore.GetRequest")
	proto.RegisterType((*GetRequest_AttributeMapEntry)(nil), "certstore.GetRequest.AttributeMapEntry")
}

func init() { proto.RegisterFile("certstore.proto", fileDescriptor_1cba6d88e0c2624b) }

var fileDescriptor_1cba6d88e0c2624b = []byte{
	// 206 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0x4e, 0x2d, 0x2a,
	0x29, 0x2e, 0xc9, 0x2f, 0x4a, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x84, 0x0b, 0x28,
	0xb1, 0x73, 0xb1, 0xba, 0xe6, 0x16, 0x94, 0x54, 0x2a, 0x29, 0x73, 0x71, 0xbb, 0xa7, 0x96, 0x04,
	0xa5, 0x16, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x0a, 0x89, 0x70, 0xb1, 0x96, 0x25, 0xe6, 0x94, 0xa6,
	0x4a, 0x30, 0x2a, 0x30, 0x6a, 0xf0, 0x04, 0x41, 0x38, 0x4a, 0x5d, 0x8c, 0x5c, 0x5c, 0x60, 0x55,
	0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0xf6, 0x5c, 0x6c, 0x89, 0x25, 0x25, 0x45, 0x99, 0x49, 0x12,
	0x8c, 0x0a, 0xcc, 0x1a, 0xdc, 0x46, 0xea, 0x7a, 0x08, 0x9b, 0x10, 0xca, 0xf4, 0x1c, 0xc1, 0x6a,
	0x4a, 0x4b, 0x52, 0x7d, 0x13, 0x0b, 0x5c, 0xf3, 0x4a, 0x8a, 0x2a, 0x83, 0xa0, 0xda, 0xa4, 0xac,
	0xb9, 0x04, 0x31, 0x24, 0x85, 0x04, 0xb8, 0x98, 0xb3, 0x53, 0x2b, 0xc1, 0x16, 0x73, 0x06, 0x81,
	0x98, 0x08, 0xc7, 0x30, 0x81, 0xc5, 0x20, 0x1c, 0x23, 0x77, 0x2e, 0x7e, 0xe7, 0xd4, 0xa2, 0x92,
	0x60, 0x90, 0x75, 0x01, 0x39, 0xa5, 0xe9, 0x99, 0x79, 0x42, 0x26, 0x5c, 0xcc, 0xee, 0xa9, 0x25,
	0x42, 0xa2, 0x58, 0xdd, 0x21, 0x25, 0x86, 0x2e, 0x0c, 0xf1, 0x6b, 0x12, 0x1b, 0x38, 0x54, 0x8c,
	0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x67, 0x16, 0xed, 0x45, 0x28, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CertStorePluginClient is the client API for CertStorePlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CertStorePluginClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
}

type certStorePluginClient struct {
	cc *grpc.ClientConn
}

func NewCertStorePluginClient(cc *grpc.ClientConn) CertStorePluginClient {
	return &certStorePluginClient{cc}
}

func (c *certStorePluginClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/certstore.CertStorePlugin/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CertStorePluginServer is the server API for CertStorePlugin service.
type CertStorePluginServer interface {
	Get(context.Context, *GetRequest) (*GetResponse, error)
}

// UnimplementedCertStorePluginServer can be embedded to have forward compatible implementations.
type UnimplementedCertStorePluginServer struct {
}

func (*UnimplementedCertStorePluginServer) Get(ctx context.Context, req *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}

func RegisterCertStorePluginServer(s *grpc.Server, srv CertStorePluginServer) {
	s.RegisterService(&_CertStorePlugin_serviceDesc, srv)
}

func _CertStorePlugin_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertStorePluginServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/certstore.CertStorePlugin/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertStorePluginServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CertStorePlugin_serviceDesc = grpc.ServiceDesc{
	ServiceName: "certstore.CertStorePlugin",
	HandlerType: (*CertStorePluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _CertStorePlugin_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "certstore.proto",
}
