apiVersion: config.ratify.deislabs.io/v1beta1
kind: Verifier
metadata:
  name: verifier-sbom
spec:
  name: sbom
  artifactTypes: application/vnd.ratify.spdx.v0
  parameters:
    disallowedPackages:
    - name: bash
      versionInfo: abc123
    disallowedLicenses: 
    - MIT
    - GPL-2.0-only
    nestedReferences: application/vnd.cncf.notary.signature
      