apiVersion: config.ratify.deislabs.io/v1alpha1
kind: Verifier
metadata:
  name: verifier-notary
spec:
  name: notaryv2
  artifactTypes: application/vnd.cncf.notary.v2.signature
  parameters:
    verificationCerts: 
    #- ~/.config/notation/certificate/june71.io.crt
    - /usr/local/ratify-certs
     