{{- if .Values.akvCertConfig.enabled }}
apiVersion: config.ratify.deislabs.io/v1beta1
kind: KeyManagementProvider
metadata:
  name: kmprovider-akv
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "5"
spec:
  type: azurekeyvault
  parameters:
    vaultURI: {{ required "vaultURI must be provided when AKV cert config is enabled" .Values.akvCertConfig.vaultURI  }}
    certificates:
      {{- if .Values.akvCertConfig.cert1Name }}
      - name: {{ .Values.akvCertConfig.cert1Name  }}
        version: {{ .Values.akvCertConfig.cert1Version  }}
      {{ end }}    
      {{- if .Values.akvCertConfig.cert2Name }}
      - name: {{ .Values.akvCertConfig.cert2Name  }}
        version: {{ .Values.akvCertConfig.cert2Version  }}        
      {{ end }}
      {{-  range .Values.akvCertConfig.certificates }}
      {{- if .name }}
      - name: {{ .name  }}
        version: {{ .version  }}
      {{- end }}
      {{- end }}
    tenantID: {{ required "tenantID must be provided when AKV cert config is enabled" .Values.akvCertConfig.tenantId  }}    
    clientID: {{ required "clientID must be provided when use workload identity in akv" .Values.azureWorkloadIdentity.clientId  }}
{{ end }}