apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ratify.fullname" . }}-certificate
data:
  ratify-test.crt: {{ .Values.ratifyTestCert | b64enc | quote }}
  {{- if .Values.cosign.enabled }}
  cosign.pub: {{ .Values.cosign.key | b64enc | quote }}
  {{- end }}
 
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ratify.fullname" . }}-tls
data:
  tls.crt: {{ .Values.provider.tls.crt | b64enc | quote }}  
  tls.key: {{ .Values.provider.tls.key | b64enc | quote }}