name: build-pr

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup go environment
        uses: actions/setup-go@v3
        with:
          go-version: "1.17"
      - name: Build CLI
        run: make
      - name: Check build
        run: bin/ratify version
