name: e2e-tests

on:
  workflow_call:

jobs:
  check-license:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
      - name: Check license header
        uses: apache/skywalking-eyes/header@ed436a5593c63a25f394ea29da61b0ac3731a9fe
        with:
          mode: check
          config: .github/licenserc.yml
      - name: Check dependencies license
        uses: apache/skywalking-eyes/dependency@ed436a5593c63a25f394ea29da61b0ac3731a9fe
        with:
          config: .github/licenserc.yml
          flags:
            --weak-compatible=true