name: Merge staging Into Main

on:
  push:
    branches:
      - 'staging'

jobs:
  main:
    name: Create PR Release to Main
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: create pull request
        run: gh pr create --title "[Automated] ${{ github.event.head_commit.message }} into main" -B main -H staging --body "Automated PR from staging to main"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}    