name: publish-sample

on: 
 workflow_dispatch:

env:
  REGISTRY: ghcr.io

permissions:
  contents: read

jobs:
  build-publish-release:
    name: "release"
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: write
      packages: write
    steps:
       
      # need to convert repo name to lowercase for Docker
      - name: Get repo
        run: |
          echo "REPO_OWNER=$(echo $GITHUB_REPOSITORY_OWNER | awk '{print tolower($0)}')" >> $GITHUB_ENV

      - name: Log in to the GHCR
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Copy signed sample  
        run: make oras-copy-sample-signed \
           SOURCE_IMG=wabbitnetworks.azurecr.io/test/notary-image:signed \
           TARGET_IMG=${{ env.REGISTRY }}/${REPO_OWNER}/test/notary-image:signed

      - name: Copy unsigned sample  
        run: make oras-copy-sample-unsigned \
           SOURCE_IMG=wabbitnetworks.azurecr.io/test/notary-image:unsigned \
           TARGET_IMG=${{ env.REGISTRY }}/${REPO_OWNER}/test/notary-image:unsigned
        