name: Sync GH Pages
on:
  push:
    branches:
    - main
    paths:
    - library/**
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - uses: everlytic/branch-merge@1.1.5
        with:
          github_token: ${{ github.token }}
          source_ref: ${{ github.ref }}
          target_branch: 'gh-pages'
          commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'